server:
  port: 8888
spring:
  application:
    name: jiang-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/
  security:
    user:
      name: admin
      password: admin
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer2:8762/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@peer1:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
