server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    healthcheck:
      enabled: true # 启用健康认证
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer2:8762/eureka/
  server:
    enable-self-preservation: false # 自我保护机制，开发环境关闭 生产环境打开
